export interface P2CRuntimeTab {
  name: string;
  description: string;
  headers: readonly string[];
}

export const P2C_SCRIPT_VERSION = 'p2c-runtime-1.3.0';

export const P2C_SYNC_LOG_HEADERS = [
  'timestamp',
  'status',
  'row_counts_by_tab_json',
  'script_version',
  'duration_ms',
  'error_message',
  'account_timezone',
  'freshness_minutes',
  'mode',
  'dry_run',
  'date_range_start',
  'date_range_end',
  'max_rows',
  'limit',
] as const;

const metricHeaders = [
  'date',
  'account_id',
  'customer_id',
  'source_sheet_id',
  'campaign_id',
  'campaign_name',
  'impressions',
  'clicks',
  'cost_micros',
  'cost',
  'conversions',
  'conversion_value',
] as const;

export const P2C_ADS_EXPORT_TABS: readonly P2CRuntimeTab[] = [
  {
    name: 'config',
    description: 'Operator-owned runtime config for script limits, date range, timezone, and dry-run behavior.',
    headers: ['key', 'value', 'description'],
  },
  {
    name: 'sync_log',
    description: 'Append-only script run log with JSON row counts, script_version, duration_ms, and errors.',
    headers: P2C_SYNC_LOG_HEADERS,
  },
  {
    name: 'raw_campaign_daily',
    description: 'Campaign/day Google Ads facts with cost_micros and normalized cost.',
    headers: [
      ...metricHeaders,
      'campaign_status',
      'serving_status',
      'channel',
      'bidding_strategy_type',
      'daily_budget',
    ],
  },
  {
    name: 'raw_adgroup_daily',
    description: 'Ad-group/day Google Ads facts with stable ad group identifiers.',
    headers: [
      ...metricHeaders,
      'ad_group_id',
      'ad_group_name',
      'ad_group_status',
      'bidding_strategy_type',
      'ad_group_cpc_bid',
    ],
  },
  {
    name: 'raw_keyword_daily',
    description: 'Keyword/day Google Ads facts with stable keyword identifiers.',
    headers: [
      ...metricHeaders,
      'ad_group_id',
      'ad_group_name',
      'criterion_id',
      'keyword',
      'match_type',
      'keyword_status',
      'device',
    ],
  },
  {
    name: 'raw_search_term_daily',
    description: 'Search-term/day Google Ads facts for diagnostics and negative candidates.',
    headers: [
      ...metricHeaders,
      'ad_group_id',
      'ad_group_name',
      'search_term',
      'search_term_status',
    ],
  },
  {
    name: 'raw_hour_device',
    description: 'Hour/device facts for time and device diagnostics.',
    headers: [
      ...metricHeaders,
      'hour',
      'device',
    ],
  },
  {
    name: 'raw_policy',
    description: 'Ad policy and approval snapshot.',
    headers: [
      'account_id',
      'customer_id',
      'source_sheet_id',
      'campaign_id',
      'campaign_name',
      'ad_group_id',
      'ad_group_name',
      'ad_id',
      'ad_status',
      'approval_status',
      'review_status',
      'final_urls',
    ],
  },
  {
    name: 'raw_pmax_channel_daily',
    description: 'Performance Max daily channel rollup with asset group context.',
    headers: [
      ...metricHeaders,
      'asset_group_id',
      'asset_group_name',
      'channel_name',
    ],
  },
  {
    name: 'raw_pmax_terms_daily',
    description: 'Performance Max search-term insight rows with asset group context.',
    headers: [
      ...metricHeaders,
      'asset_group_id',
      'asset_group_name',
      'term_text',
      'term_source',
    ],
  },
  {
    name: 'raw_geo_daily',
    description: 'Daily geo facts keyed by country and optional region/city.',
    headers: [
      ...metricHeaders,
      'country_criterion_id',
      'country_code',
      'region',
      'city',
    ],
  },
  {
    name: 'raw_placement_daily',
    description: 'Daily placement facts for placement and content suitability diagnostics.',
    headers: [
      ...metricHeaders,
      'ad_group_id',
      'ad_group_name',
      'placement',
      'placement_type',
    ],
  },
  {
    name: 'raw_budget_daily',
    description: 'Daily budget pacing facts from campaign budget and spend.',
    headers: [
      'date',
      'account_id',
      'customer_id',
      'source_sheet_id',
      'campaign_id',
      'campaign_name',
      'daily_budget',
      'cost',
      'budget_lost_impression_share',
      'budget_remaining',
      'budget_utilization',
    ],
  },
  {
    name: 'raw_conversion_action_daily',
    description: 'Daily conversion action facts with stable conversion action identifiers.',
    headers: [
      'date',
      'account_id',
      'customer_id',
      'source_sheet_id',
      'campaign_id',
      'campaign_name',
      'conversion_action_id',
      'conversion_action_name',
      'category',
      'primary_for_goal',
      'include_in_conversions_metric',
      'conversions',
      'conversion_value',
      'all_conversions',
    ],
  },
];

export const P2C_APPS_SCRIPT_TABS: readonly P2CRuntimeTab[] = [
  ...P2C_ADS_EXPORT_TABS,
  {
    name: 'raw_leadingcards_cards',
    description: 'LeadingCards card metadata used for matching and audit.',
    headers: [
      'card_uuid',
      'card_id',
      'card_repr_id',
      'last4',
      'censored_number',
      'bin_name',
      'bin_currency',
      'issuer_name',
      'team_uuid',
      'team_name',
      'status',
      'fetched_at',
      'raw_hash',
    ],
  },
  {
    name: 'raw_leadingcards_teams',
    description: 'LeadingCards teams for display and optional matching context.',
    headers: [
      'team_uuid',
      'name',
      'slug',
      'status',
      'fetched_at',
      'raw_hash',
    ],
  },
  {
    name: 'raw_leadingcards_transactions',
    description: 'LeadingCards transactions with safe fields only.',
    headers: [
      'transaction_uuid',
      'merchant',
      'transaction_at',
      'amount',
      'amount_ui',
      'local_amount',
      'local_currency',
      'status_name',
      'status_level',
      'response_text',
      'is_pending',
      'country',
      'card_uuid',
      'card_id',
      'card_repr_id',
      'last4',
      'censored_number',
      'bin_name',
      'bin_currency',
      'issuer_name',
      'fee_percentage',
      'team_name',
      'fetched_at',
      'raw_hash',
    ],
  },
  {
    name: 'leadingcards_reconciliation',
    description: 'Daily card-vs-google reconciliation snapshot generated after LC ingest.',
    headers: [
      'date',
      'google_account_id',
      'google_customer_id',
      'google_source_sheet_id',
      'google_ads_cost',
      'approved_amount',
      'pending_amount',
      'failed_amount',
      'refunded_amount',
      'estimated_fees',
      'leadingcards_local_amount',
      'spend_delta',
      'spend_delta_percent',
      'reconciliation_status',
      'reason',
      'transaction_count',
      'mapping_id',
    ],
  },
] as const;

export const P2C_RUNTIME_TABS = P2C_APPS_SCRIPT_TABS;

export const P2C_APPS_SCRIPT_ENDPOINTS = [
  'health',
  'accounts',
  'config',
  'sync_log',
  'raw_campaign_daily',
  'raw_adgroup_daily',
  'raw_keyword_daily',
  'raw_search_term_daily',
  'raw_hour_device',
  'raw_policy',
  'raw_pmax_channel_daily',
  'raw_pmax_terms_daily',
  'raw_geo_daily',
  'raw_placement_daily',
  'raw_budget_daily',
  'raw_conversion_action_daily',
  'raw_leadingcards_cards',
  'raw_leadingcards_teams',
  'raw_leadingcards_transactions',
  'leadingcards_reconciliation',
  'analysis_reconciliation',
] as const;
